name: Terraform Plan Graph
description: Generate a visual graph representation of Terraform plan changes
author: yu-iskw
branding:
  icon: activity
  color: blue
inputs:
  plan-file:
    description: Path to the Terraform plan JSON file
    required: true
  format:
    description: Output format (graphviz, mermaid, plantuml)
    required: false
    default: graphviz
  output-file:
    description: Output file path (default - stdout)
    required: false
    default: ""
  group-by:
    description: Grouping strategy (module, action, resource_type)
    required: false
    default: module
  no-data-sources:
    description: Exclude data source resources from the graph
    required: false
    default: "false"
  no-outputs:
    description: Exclude output values from the graph
    required: false
    default: "false"
  no-variables:
    description: Exclude variable values from the graph
    required: false
    default: "false"
  no-locals:
    description: Exclude local values from the graph
    required: false
    default: "false"
  no-modules:
    description: Exclude resources from modules from the graph
    required: false
    default: "false"
  compact:
    description: Generate a more compact graph layout
    required: false
    default: "false"
  verbose:
    description: Enable verbose output for debugging
    required: false
    default: "false"
outputs:
  graph-content:
    description: The generated graph content (when output-file is not specified)
  output-file-path:
    description: Path to the generated output file (when output-file is specified)
runs:
  using: docker
  image: Dockerfile
